# Develop profile (don't communicate with services, only send information to console)
spring.config.activate.on-profile=develop
# Telegram_develop
tg.username=testjavakirbot
tg.token=8797926452:AAFhB6cfLNWPFhVZm050SLMdZLmA7b3mdHM
